{
    "name": "job",
    "application": True,
    "summary": "This appluication for JOB .",
    "version": "1.0.0",
    "category": "",
    "website": "www.asjhaskjd/saasg/sjdhj",
    "author": "Chirag Vaghasiya",
    "license": "",
    "installable": True,
    "depends": ['hr_recruitment'],
    "development_status": "",
    "maintainers": [],
    'demo':[],
    "excludes": [],
    "data": [
        'security/ir.model.access.csv',
        'views/menu.xml',
        'views/generate_job_view.xml',
        'views/job_status_view.xml',
    ],
    "sequence": -500,
    'license': 'LGPL-3',
}